name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List all files for debugging
        run: ls -la
        working-directory: app

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execution permission for Gradlew
        working-directory: app
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: app
        run: ./gradlew build